### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by joshuamaxwell**
Mark, I'm still pretty new to programming culture so I don't know if this is trolling or not, but I assure you that is not my goal. I'm not very familiar with CoffeeScript... and the only way I know how to use backbonejs is the way Mason is teaching us, so I have a somewhat narrow understanding of both.

I made some changes inside the "Step 4:" section and I'm wondering how the way you did it would work? Are they typos, or just a different way of making backbone views? Are you going to talk about this at greenvillejs? if so, I can't wait!

### CODE REVIEW

**Comment by agborkowski** [comment]
i dont like coffe too ;) anyway good tut

**Comment by rbishop** [comment]
I don't think this is trolling. Writing a long tutorial like this is a lot of work and energy and we all make little mistakes. I noticed these same things when reading the `tutorial.md` and was going to submit a PR but I'm glad someone beat me to it :)

I do think `className` should still be `el` though because he is setting `el` to a CSS ID selector, not a class selector.

I'm not sure if you want to add this to your PR, but another related change I would make is changing the following:

``` coffeescript
$ ->
  model = new Backbone.Model()
  new ContactFormView(model: model).render()
  new ContactView(model: model).render()
```

to:

``` coffeescript
$ ->
  model = new ContactModel()
  new ContactFormView(model: model).render()
  new ContactView(model: model).render()
```

Also, thank you for your work on this @wmdmark!

**Comment by wmdmark** [comment]
@joshuamaxwell Good catch Josh, and no you're definitely not trolling! The "el" attribute is correct but the tutorial code was not extending from Backbone.View so I'll fix that for sure. If it helps, this is how the ContactFormView would look in JS: https://gist.github.com/wmdmark/9371351

@rbishop Thanks for pointing out the typo there! Will fix momentarily. 

@agborkowski CoffeeScript isn't for everyone, but it has some benefits. I recommend watching this video if you're on the fence about it: http://www.youtube.com/watch?v=RoPnnkYg9nI

**Comment by joshuamaxwell** [comment]
Awesome.And I'm looking forward to picking up some coffee script. Thanks for the tutorial!

**Pull request closed without merging**
